---- Base app schema
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  username varchar(128) NOT NULL UNIQUE,
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT uuid_generate_v4(),
  token_salt uuid NOT NULL DEFAULT uuid_generate_v4()
);
-- Task
Create TABLE "task" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  title varchar(256) NOT NULL
);